org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

modGroup=com.lambda
modVersion=1.1

minecraftVersion=1.12.2
forgeVersion=14.23.5.2860
mappingsChannel=stable
mappingsVersion=39-1.12

kotlinVersion=1.8.20
kotlinxCoroutinesVersion=1.7.0-RC

systemProp.org.gradle.internal.http.connectionTimeout=120000
systemProp.org.gradle.internal.http.socketTimeout=120000
systemProp.org.gradle.internal.repository.max.tentatives=5
systemProp.org.gradle.internal.repository.initial.backoff=1000